cd codeforces-problem-solving ; git pull ; cd .. ;
echo " codeforces-problem-solving's pulling is successfull!!!! al-hamdulillah ***";
cd IntroductionToGitAndGithub ; git pull ; cd ..; 
echo " IntroductionToGitAndGithub's pulling is successfull!!!! al-hamdulillah ***";
cd CodingBookMarks ; git pull ; cd .. ;      
echo " CodingBookMarks's pulling is successfull!!!! al-hamdulillah ***";       
cd combinatorial-optimization ; git pull ; cd .. ; 
echo " combinatorial-optimization's pulling is successfull!!!! al-hamdulillah ***";
cd numerical-analysis ; git pull ; cd .. ; 
echo " numerical-analysis's pulling is successfull!!!! al-hamdulillah ***";
cd Coursera ; git pull ; cd .. ; 
echo " Coursera's pulling is successfull!!!! al-hamdulillah ***";
cd OperatingSystem ; git pull ; cd .. ; 
echo " OperatingSystem's pulling is successfull!!!! al-hamdulillah ***";
cd data-structure-algorithm ; git pull ; cd .. ; 
echo " data-structure-algorithm's pulling is successfull!!!! al-hamdulillah ***";
cd ProgrammingContestMaterials ; git pull ; cd .. ; 
echo " 's pulling is successfull!!!! al-hamdulillah ***";
cd RiLanguageCenter ; git pull ; cd .. ; 
echo " ProgrammingContestMaterials's pulling is successfull!!!! al-hamdulillah ***";
cd hackkerrank-problem-solving  ; git pull ; cd .. ;  
echo " hackkerrank-problem-solving 's pulling is successfull!!!! al-hamdulillah ***";
cd RoadToICPC ; git pull ; cd .. ; 
echo " RoadToICPC's pulling is successfull!!!! al-hamdulillah ***";
cd virtual-judge-problem-solving ; git pull ; cd .. ; 
echo " virtual-judge-problem-solving's pulling is successfull!!!! al-hamdulillah ***";
cd InformationSecurity ; git pull ; cd .. ; 
echo " InformationSecurity's pulling is successfull!!!! al-hamdulillah ***";

